### ISSUE TITLE
Code example needed

### ISSUE THREAD

**Issue by stax76** [bartbes/inifile#3]
How do I use `sectionorder`? Anybody, please help with a working code example. Unfortunately, my Lua knowledge is limited, in particular advanced functionality like metatables.

**Comment by bartbes** [comment]
What are you trying to do? `sectionorder` is mostly an implementation detail for how this library mostly reproduces the input file when saving again.

The library basically works as follows (see example ini below):
```lua
local inifile = require("inifile")
local data = inifile.parse("some.ini")
print(data.general.stuff) -- 3
data.grass.color = "greener"
inifile.save("output.ini", data)
```

With the following input ("some.ini"):
```ini
[general]
stuff=3
otherStuff=text

[grass]
color=green
```

And the output file ("output.ini") would then look like:
```ini
[general]
stuff=3
otherStuff=text

[grass]
color=greener
```

In particular, the stored `sectionorder` stuff is all about being able to write the file back out in the same order (as seen in the example), rather than whatever order lua happens to choose to store the table in.
